forecast script

diff --git a/forecast b/forecast
--- a/forecast
+++ b/forecast
@@ -2,6 +2,14 @@
 
 source ./config.sh
 
+if [[ ! "$STACK_NAME" =~ ^[a-z][a-z0-9]*$ ]]
+then
+
+  echo "ERROR: STACK_NAME must start with a lower case letter and contain only lower case letters and numbers"
+  exit 1
+
+fi
+
 if ! [ -x "$(command -v aws)" ]
 then
 
